[package]
name = "CombiNBT"
version = "0.1.0"
edition = "2024"

[dependencies]
fastnbt = "2.6.0"
flate2 = "1.1.5"
serde = { version = "1.0.228", features = ["derive"] }
log = "0.4.29"
thiserror = "2.0.17"
